/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var S=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var f=Object.prototype.hasOwnProperty;var w=(a,e)=>{for(var t in e)o(a,t,{get:e[t],enumerable:!0})},T=(a,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of d(e))!f.call(a,s)&&s!==t&&o(a,s,{get:()=>e[s],enumerable:!(i=S(e,s))||i.enumerable});return a};var m=a=>T(o({},"__esModule",{value:!0}),a);var y={};w(y,{default:()=>r});module.exports=m(y);var p=require("obsidian");var g=require("obsidian"),n="csv-view",l=class extends g.TextFileView{getViewData(){return this.tableData.map(t=>t.join(",")).join(`
`)}setViewData(t,i){this.tableData=t.split(`
`).map(s=>s.split(",")),this.refresh()}refresh(){this.tableEl.empty();let t=this.tableEl.createEl("tbody");this.tableData.forEach((i,s)=>{let h=t.createEl("tr");i.forEach((E,u)=>{let b=h.createEl("td").createEl("input",{attr:{value:E}});b.oninput=c=>{c.currentTarget instanceof HTMLInputElement&&(this.tableData[s][u]=c.currentTarget.value,this.requestSave())}})})}clear(){this.tableData=[]}getViewType(){return n}async onOpen(){this.tableEl=this.contentEl.createEl("table")}async onClose(){this.contentEl.empty()}};var V={csvSettings:"default"},r=class extends p.Plugin{async onload(){await this.loadSettings(),this.registerView(n,t=>new l(t)),this.registerExtensions(["csv"],n)}onunload(){this.app.workspace.detachLeavesOfType(n)}async loadSettings(){this.settings=Object.assign({},V,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}};

/* nosourcemap */